export const CATEGORY_ICON_OPTIONS: string[][] = [
  [''],
  ['BasketFill', 'BasketFill2', 'Cart', 'CartFill', 'FastFood', 'Cafe', 'Cup'],
  ['Cloth', 'Shoes', 'Watch'],
  [
    'Car',
    'CarFill',
    'Parking',
    'FuelPump',
    'Bus',
    'BusFill',
    'Taxi',
    'TruckFront',
    'Truck',
    'Airplane',
    'AirplaneFill',
    'Train',
    'TrainFill',
    'Scooter',
    'Bicycle',
  ],
  ['Rosneft', 'Sberbank', 'VTB', 'Tinkoff', 'AlfaBank', 'GazpromBank', 'Raiffeisen'],
  ['FileText', 'FileTextFill', 'Droplet', 'Globe2', 'WIFI', 'RouterFill', 'SIMFill'],
  ['MusicNote', 'Film', 'Wine', 'Ticket', 'TicketFill', 'Suitcase', 'SuitcaseFill', 'Backpack', 'BackpackFill'],
  ['CPU', 'Phone', 'Telephone', 'TelephoneFill', 'Display', 'DisplayPC', 'Controller', 'Headset'],
  [
    'Cash',
    'CashCoin',
    'CashStack',
    'Wallet',
    'WalletFill',
    'Card',
    'CardFill',
    'Bank',
    'PiggyBank',
    'Percent',
    'GraphArrow',
    'BarChartLineFill',
  ],
  ['Furniture', 'Spray', 'Washing', 'Hammer', 'Tools', 'Brush'],
  ['House', 'HouseFill', 'Building', 'BuildingFill', 'Buildings', 'BuildingsFill'],
  ['Book', 'BookFill', 'Journal', 'HatGraduate'],
  ['Cross', 'Capsule', 'CapsulePill', 'Hospital', 'HospitalFill', 'Tooth', 'Stethoscope'],
  ['Scissors', 'Toothbrush', 'Cream', 'Pomade', 'Nail'],
  ['Dumbbell', 'Ball'],
  ['Family', 'Children', 'GiftFill', 'Pet', 'Toys'],
];
